INSERT INTO egf_instrumenttype (id, name, description, active, createdby, createddate, lastmodifiedby, lastmodifieddate, tenantid, version)
SELECT md5('instrumenttype:' || t.tenantid || ':' || it.name)::uuid::text, it.name, it.description, true, '1', now(), '1', now(), t.tenantid, 0
FROM (VALUES
    ('Cash', 'Instrument type cash'),
    ('Cheque', 'Instrument type cheque'),
    ('DD', 'Instrument type dd'),
    ('Online', 'Instrument type online'),
    ('Advice', 'Instrument type advice'),
    ('BankChallan', 'Instrument type bank challan'),
    ('Card', 'Instrument type card'),
    ('BankToBank', 'Instrument type bank to bank')
) AS it (name, description)
CROSS JOIN (VALUES
    ('hp.Amb'),
    ('hp.amb'),
    ('hp.Arki'),
    ('hp.arki'),
    ('hp.Baddi'),
    ('hp.baddi'),
    ('hp.BaijnathPaprola'),
    ('hp.baijnathpaprola'),
    ('hp.Banjar'),
    ('hp.banjar'),
    ('hp.Bhota'),
    ('hp.bhota'),
    ('hp.Bhuntar'),
    ('hp.bhuntar'),
    ('hp.Bilaspur'),
    ('hp.bilaspur'),
    ('hp.Chamba'),
    ('hp.chamba'),
    ('hp.Chirgaon'),
    ('hp.chirgaon'),
    ('hp.Chopal'),
    ('hp.chopal'),
    ('hp.Chowari'),
    ('hp.chowari'),
    ('hp.Dalhousie'),
    ('hp.dalhousie'),
    ('hp.Daulatpur'),
    ('hp.daulatpur'),
    ('hp.Dehra'),
    ('hp.dehra'),
    ('hp.Dharamshala'),
    ('hp.dharamshala'),
    ('hp.Gagret'),
    ('hp.gagret'),
    ('hp.Ghumarwin'),
    ('hp.ghumarwin'),
    ('hp.Hamirpur'),
    ('hp.hamirpur'),
    ('hp.Jawalamukhi'),
    ('hp.jawalamukhi'),
    ('hp.Jawali'),
    ('hp.jawali'),
    ('hp.Jogindernagar'),
    ('hp.jogindernagar'),
    ('hp.Jubbal'),
    ('hp.jubbal'),
    ('hp.Kandaghat'),
    ('hp.kandaghat'),
    ('hp.Kangra'),
    ('hp.kangra'),
    ('hp.Karsog'),
    ('hp.karsog'),
    ('hp.Kotkhai'),
    ('hp.kotkhai'),
    ('hp.Kullu'),
    ('hp.kullu'),
    ('hp.Manali'),
    ('hp.manali'),
    ('hp.Mandi'),
    ('hp.mandi'),
    ('hp.MehatpurBasdehr'),
    ('hp.mehatpurbasdehr'),
    ('hp.Nadaun'),
    ('hp.nadaun'),
    ('hp.Nagrota'),
    ('hp.nagrota'),
    ('hp.Nahan'),
    ('hp.nahan'),
    ('hp.Nainadeviji'),
    ('hp.nainadeviji'),
    ('hp.Nalagarh'),
    ('hp.nalagarh'),
    ('hp.Narkanda'),
    ('hp.narkanda'),
    ('hp.NerChowk'),
    ('hp.nerchowk'),
    ('hp.Nerwa'),
    ('hp.nerwa'),
    ('hp.Nirmand'),
    ('hp.nirmand'),
    ('hp.Nurpur'),
    ('hp.nurpur'),
    ('hp.Palampur'),
    ('hp.palampur'),
    ('hp.Parwanoo'),
    ('hp.parwanoo'),
    ('hp.PoantaSahib'),
    ('hp.poantasahib'),
    ('hp.Rajgarh'),
    ('hp.rajgarh'),
    ('hp.Rampur'),
    ('hp.rampur'),
    ('hp.Rewalsar'),
    ('hp.rewalsar'),
    ('hp.Rohru'),
    ('hp.rohru'),
    ('hp.Santokhgarh'),
    ('hp.santokhgarh'),
    ('hp.Sarkaghat'),
    ('hp.sarkaghat'),
    ('hp.Shahpur'),
    ('hp.shahpur'),
    ('hp.Shimla'),
    ('hp.shimla'),
    ('hp.Solan'),
    ('hp.solan'),
    ('hp.Sujanpur'),
    ('hp.sujanpur'),
    ('hp.Sundernagar'),
    ('hp.sundernagar'),
    ('hp.Sunni'),
    ('hp.sunni'),
    ('hp.Tahliwal'),
    ('hp.tahliwal'),
    ('hp.Talai'),
    ('hp.talai'),
    ('hp.Theog'),
    ('hp.theog'),
    ('hp.Una'),
    ('hp.una')
) AS t (tenantid)
WHERE NOT EXISTS (
    SELECT 1 FROM egf_instrumenttype e WHERE e.name = it.name AND e.tenantid = t.tenantid
);
