spring.application.name=digital-door-plate
server.port=${SERVER_PORT:1239}
server.contextPath=/digital-door-plate
server.servlet.context-path=/digital-door-plate

# health check for k8s probes at /digital-door-plate/health
management.endpoints.web.base-path=/

# Application Settings
state.level.tenant.id=hp

app.timezone=Asia/Kolkata
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/hp_udd_dev
spring.datasource.username=postgres
spring.datasource.password=postgres

##----------------------------- FLYWAY CONFIGURATIONS ------------------------------#
spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5432/hp_udd_dev
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.table=digital_door_plate_schema
spring.flyway.locations=classpath:db/migration/ddl
spring.flyway.baseline-on-migrate=true
spring.flyway.out-of-order=true

##----------------------------- enc service ------------------------------#
egov.enc.host=http://localhost:1234
egov.enc.encrypt.endpoint=/egov-enc-service/crypto/v1/_encrypt
egov.enc.decrypt.endpoint=/egov-enc-service/crypto/v1/_decrypt

##----------------------------- garbage service ------------------------------#
egov.garbage.service.host=http://localhost:1235
egov.garbage.account.search.endpoint=/garbage-service/garbage-accounts/_search
